# apps/service-1/manifest.yaml
apiVersion: v1
kind: Service
metadata:
  name: service-1
  namespace: service-1
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: service-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1
  namespace: service-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-1
  template:
    metadata:
      labels:
        app: service-1
    spec:
      serviceAccountName: service-1-sa
      containers:
      - name: app
        image: curlimages/curl:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            while true; do 
              echo -e "HTTP/1.1 200 OK\n\n Service 1 is up" | nc -l -p 80; 
            done & 
            sleep infinity
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-1-sa
  namespace: service-1
---
# GATEWAY: Abre a porta de entrada do Cluster
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: service-1-gateway
  namespace: service-1
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
# VIRTUAL SERVICE 1: Entrada (Roteia o Ingress Gateway para o Service-1)
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service-1-vs
  namespace: service-1
spec:
  hosts:
  - "service-1.local"
  gateways:
  - service-1-gateway
  http:
  - route:
    - destination:
        host: service-1.service-1.svc.cluster.local
        port:
          number: 80
---
# VIRTUAL SERVICE 2: (Roteamento do Service-1 para o Service-2)
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: route-to-service-2
  namespace: service-1
spec:
  hosts:
  - service-2.service-2.svc.cluster.local
  http:
  - route:
    - destination:
        host: service-2.service-2.svc.cluster.local
        port:
          number: 80
---
# JWT: Validação de quem entra
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-auth
  namespace: service-1
spec:
  selector:
    matchLabels:
      app: service-1
  jwtRules:
  - issuer: "testing@secure.istio.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/master/security/tools/jwt/samples/jwks.json"
---
# AUTH POLICY: Proíbe acesso sem JWT
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: require-jwt
  namespace: service-1
spec:
  selector:
    matchLabels:
      app: service-1
  action: ALLOW
  rules:
  - from:
    - source:
        requestPrincipals: ["testing@secure.istio.io/*"]
---
# DESTINATION RULE: Força mTLS para o serviço-2, garantindo que a comunicação entre os serviços seja segura 
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: mtls-to-service-2
  namespace: service-1
spec:
  host: service-2.service-2.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL