require 'securerandom'
token_file = ".k3s_token"

if File.exist?(token_file)
  K3S_TOKEN = File.read(token_file).strip
else
  K3S_TOKEN = SecureRandom.hex(16) # Gera um token aleatório
  File.write(token_file, K3S_TOKEN)
end

Vagrant.configure("2") do |config|
    config.vm.box = "generic/ubuntu2204"
    config.vm.synced_folder "../../environment", "/home/vagrant/environment", type: "rsync"
    
    # Token fixo para os agentes conseguirem se juntar ao servidor
    K3S_TOKEN = "token-secreto-desafio-devops"
  
    # ==========================================
    # NÓ 1: O Control Plane (Servidor)
    # ==========================================
    config.vm.define "server" do |server|
      server.vm.hostname = "server"
      server.vm.network "private_network", ip: "192.168.56.10"
      server.vm.provider :libvirt do |lv|
        lv.memory = 4096 # O server vai precisar rodar a API do K8s e futuramente o Istiod
        lv.cpus = 2
      end
      
      # 1. Instalação do K3s
      server.vm.provision "shell", inline: <<-SHELL
      echo "Subindo o Control Plane..."
      curl -sfL https://get.k3s.io | K3S_TOKEN=#{K3S_TOKEN} INSTALL_K3S_EXEC="server --disable traefik --write-kubeconfig-mode 644 --node-taint CriticalAddonsOnly=true:NoExecute" sh -
      
      # Aguarda o arquivo de configuração estar pronto antes de prosseguir
      until [ -f /etc/rancher/k3s/k3s.yaml ]; do sleep 2; done
      echo "K3s pronto!"
      SHELL

      # 2. Execução do Bootstrap de Aplicação (KEDA, Prometheus, services 1-3)
      server.vm.provision "shell", inline: <<-SHELL
        sudo chmod 644 /etc/rancher/k3s/k3s.yaml
        
        if ! grep -q "KUBECONFIG" /home/vagrant/.bashrc; then
          echo 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml' >> /home/vagrant/.bashrc
        fi
        
        bash /home/vagrant/environment/vagrant/bootstrap.sh
      SHELL
    end
  
    # ==========================================
    # NÓS 2 e 3: Os Agentes (Workers)
    # ==========================================
    (1..2).each do |i|
      config.vm.define "agent-#{i}" do |agent|
        agent.vm.hostname = "agent-#{i}"

        # Os IPs serão 192.168.56.11 e 192.168.56.12
        agent.vm.network "private_network", ip: "192.168.56.1#{i}"
        agent.vm.provider :libvirt do |lv|
          lv.memory = 2048 # Metade da RAM pra cada worker
          lv.cpus = 2
        end
        
        agent.vm.provision "shell", inline: <<-SHELL
          echo "Ingressando Agente #{i} no cluster..."
          # O agente aponta para o IP do servidor e usa o mesmo token
          curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.10:6443 K3S_TOKEN=#{K3S_TOKEN} sh -
        SHELL
      end
    end
  end