# apps/service-2/chart/values.yaml
replicaCount: 1

image:
  repository: curlimages/curl
  tag: "latest"
  pullPolicy: IfNotPresent
command: ["/bin/sh", "-c"]
args: ["while true; do echo -e 'HTTP/1.1 200 OK\n\n Service 2 is up' | nc -l -p 80; done & sleep infinity"]
service:
  type: ClusterIP
  port: 80

authPolicy:
  allowFrom:
    - "service-1"